# Generated by Django 5.0.3 on 2024-04-11 01:33

import api.video.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.CharField(max_length=30, verbose_name='タイトル')),
                ('video', models.FileField(upload_to=api.video.models.load_path_video, verbose_name='動画')),
                ('thumbnail', models.ImageField(upload_to=api.video.models.load_path_thumbnail, verbose_name='サムネイル')),
                ('size', models.BigIntegerField(default=0, verbose_name='動画サイズ')),
                ('like', models.IntegerField(default=0, verbose_name='ライク')),
                ('dislike', models.IntegerField(default=0, verbose_name='ディスライク')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
    ]
