# Generated by Django 5.0.3 on 2024-04-05 00:50

import api.video.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('video', models.FileField(upload_to=api.video.models.load_path_video)),
                ('thumbnail', models.ImageField(upload_to=api.video.models.load_path_thumbnail)),
                ('like', models.IntegerField(default=0)),
                ('dislike', models.IntegerField(default=0)),
            ],
        ),
    ]
