# Generated by Django 5.0.3 on 2024-04-08 05:27

import api.video.models
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='投稿日時'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='size',
            field=models.BigIntegerField(default=0, verbose_name='動画サイズ'),
        ),
        migrations.AddField(
            model_name='video',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='video',
            name='dislike',
            field=models.IntegerField(default=0, verbose_name='ディスライク'),
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='video',
            name='like',
            field=models.IntegerField(default=0, verbose_name='ライク'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(upload_to=api.video.models.load_path_thumbnail, verbose_name='サムネイル'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=30, verbose_name='タイトル'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to=api.video.models.load_path_video, verbose_name='動画'),
        ),
    ]
