# Generated by Django 5.0.3 on 2024-04-12 04:05

import api.video.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(upload_to=api.video.models.get_thumbnail_upload_path, verbose_name='サムネイル'),
        ),
    ]
