# Generated by Django 5.0.3 on 2024-04-11 07:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=255, verbose_name='会社名')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='メールアドレス')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効フラグ')),
                ('is_staff', models.BooleanField(default=False, verbose_name='管理サイトアクセス権限')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日時')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='会社名')),
                ('plan', models.IntegerField(choices=[(1, '無料'), (2, 'スタンダード'), (3, 'プレミアム')], default=1, verbose_name='プラン')),
                ('occupation', models.CharField(blank=True, max_length=50, verbose_name='職業')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='住所')),
                ('phone', models.CharField(blank=True, max_length=255, verbose_name='電話番号')),
                ('age', models.CharField(blank=True, max_length=255, verbose_name='年齢')),
                ('gendar', models.CharField(blank=True, choices=[('女性', '女性'), ('男性', '男性')], max_length=2, verbose_name='性別')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
