# Generated by Django 5.0.3 on 2024-04-11 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=255, verbose_name='会社名'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gendar',
            field=models.CharField(blank=True, choices=[('女性', '女性'), ('男性', '男性')], max_length=2, verbose_name='性別'),
        ),
    ]
